apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:  # This spec is now correctly nested inside template
      containers:
        - name: website-container
          image: nginx:latest # Or your website's image
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-data
              mountPath: /usr/share/nginx/html # Or the appropriate path for your web server
      volumes:
        - name: website-data
          persistentVolumeClaim:
            claimName: website-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-pvc
spec:
  accessModes:
    - ReadWriteOnce # Or ReadOnlyMany if applicable
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn # Replace with your Longhorn StorageClass name if different

---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80 # The port that the service exposes
    targetPort: 80 # The port the container is listening on
    nodePort: 30009 # Choose a port between 30000-32767
  type: NodePort
