apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website-container
        image: nginx:latest # Or your preferred web server image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-data
          mountPath: /usr/share/nginx/html # Or the appropriate path for your web server
      volumes:
      - name: website-data
        persistentVolumeClaim:
          claimName: website-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-pvc
spec:
  accessModes:
    - ReadWriteOnce # Or ReadOnlyMany if applicable
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn # Replace with your Longhorn StorageClass name if different
